In [1]:
#@ type sof arrays:
#built in arays arrays
#numpy arrays - this one ppl use

In [2]:
import numpy as np #alias fornumpy

In [4]:
list = [23254, 27, 546, 215, -1234]

In [6]:
a = np.array(list)

In [7]:
a

array([23254,    27,   546,   215, -1234])

In [8]:
#Array is like a vector in R, you cannot have different data types

In [10]:
a.max()  #lots of functions already come with arrays. 
#here we have applied function max to our array a

23254

In [11]:
a.min()

-1234

In [12]:
a.mean()

4561.6

---

In [13]:
#slicing arrays

In [14]:
a[2:]

array([  546,   215, -1234])

In [15]:
a[2:4]

array([546, 215])

In [16]:
#when you slice an array you do not create a new array 
#you just create  aview of the array and that is different from lists

In [24]:
b = a[2:4]

In [25]:
b

array([546, 215])

In [26]:
#to make a new array use copy()

In [27]:
c = a.copy()

In [28]:
c

array([23254,    27,   546,   215, -1234])